#!/usr/bin/env python

# Script modeled off this Stack answer
# https://stackoverflow.com/questions/12938581/ffmpeg-mux-video-and-audio-from-another-video-mapping-issue

import sys
from subprocess import check_output
import click

@click.command()
@click.argument('video_source')
@click.argument('audio_source')
@click.option('--output-filepath', default='blend.mkv')
def blend(video_source, audio_source, output_filepath):
    safe_filepath = lambda filepath: filepath.replace(' ', '\\ ')

    desired_visual_video = safe_filepath(video_source)
    desired_audio_video = safe_filepath(audio_source)
    output_path = safe_filepath(output_filepath)

    cross_streams_command = f'/usr/local/bin/ffmpeg -i {desired_visual_video} -i {desired_audio_video} -c copy -map 0:v:0 -map 1:a:0 -shortest {output_path}'
    check_output(cross_streams_command, shell=True)


if __name__ == '__main__':
    blend()
