#!/usr/bin/env python

from subprocess import check_output
import requests
from bs4 import BeautifulSoup
import sys
import youtube_dl
import click



@click.command()
@click.argument('search_terms', nargs=-1)
@click.option('--count', type=int, help='Number of videos to download', default=1)
@click.option('--creative-commons', is_flag=True, help='Filter to only Creative Commons videos')
@click.option('--res-4k', is_flag=True, help='Filter to only 4k resolution videos')
@click.option('--res-HD', is_flag=True, help='Filter to only HD resolution videos')
def search_and_download(search_terms, count, creative_commons, res_4k, res_hd):
    '''This script searchs for videos Youtube for Creative Commons which match the given terms, then downloads them.'''

    base_url = 'https://www.youtube.com/results?search_query='

    creative_commons_filter = '&sp=EgIwAQ%253D%253D'
    resolution_4k_filter = '&sp=EgJwAQ%253D%253D'
    creative_commons_4k_filter = '&sp=EgQwAXAB'
    resolution_HD_filter = '&sp=EgIgAQ%253D%253D'
    creative_commons_HD_filter = '&sp=EgQgATAB'

    # Create URL for the Youtube video search
    youtube_search_url = ''
    if creative_commons:
        youtube_search_url = base_url + '+'.join(search_terms) + creative_commons_filter
    if res_4k:
        youtube_search_url = base_url + '+'.join(search_terms) + resolution_4k_filter
    if res_hd:
        youtube_search_url = base_url + '+'.join(search_terms) + resolution_HD_filter
    if creative_commons and res_4k:
        youtube_search_url = base_url + '+'.join(search_terms) + creative_commons_4k_filter
    if creative_commons and res_hd:
        youtube_search_url = base_url + '+'.join(search_terms) + creative_commons_HD_filter
    if youtube_search_url == '':
        youtube_search_url = base_url + '+'.join(search_terms)

    # Request the search page from Youtube
    page = requests.get(youtube_search_url)

    # List all video elements on the search results page
    soup = BeautifulSoup(page.content, 'html.parser')
    result_videos = soup.select('.yt-lockup-title')

    for result_video in result_videos[:int(count)]:
        # Grab title and link for each video in the results
        result_title_element = result_video.find('a')
        title = result_title_element['title']
        href = result_title_element['href']
        video_url = 'http://www.youtube.com' + href

        # Download
        ydl = youtube_dl.YoutubeDL({
            'outtmpl': 'videos/' + '_'.join(search_terms) + '/' + title.replace(' ', '_').replace('"', '').replace("'", '').replace('(', '').replace(')', ''),
            'noplaylist': True
#            'logger': Logger()
        })

        with ydl:
            result = ydl.extract_info(video_url)


class Logger(object):
    def debug(self, msg):
        if '[download]' in msg:
            if 'already' in msg or 'Download' in msg:
                return
            if 'playlist' in msg or 'Destination' in msg:
                print(msg)
            else:
                sys.stdout.write(msg)

    def warning(self, msg):
        pass

    def error(self, msg):
        print(msg)


if __name__ == '__main__':
    search_and_download()
